### ISSUE TITLE
Can't use git; gives error over HTTPS, nothing over SSH

### ISSUE THREAD

**Issue by girst** [android-password-store/Android-Password-Store#137]
I tried setting up pass with our gitlab server (using a startSSL cert and custom port numbers I can't change). 

So I went into the "repository settings" and used these settings:
- Protocol: **https://**
- Username: _my_gitlab_user_name_
- Server URL: **gitlab.xxx.net** : **6943**
- Repo Path: **/my_username/pass.git**

(There is another bug: in the resulting URL the portnumber is preceded by a slash instead of a colon - I fixed that manually)

The following error occurs: 
**Internal exception occurred**
Message from jgit:
https://gitlab.xxx.net:6943/my_username/pass.git:
cannot open git-upload-pack

Using SSH:
- Protocol: **https://**
- Username: **git**
- Server URL: **gitlab.xxx.net** : **6922**
- Repo path: **/my_username/pass.git**
- Authentication Mode: **ssh-key**

No connection attempt seems to be made, and there is no confirmation/error message. 

Any help is highly appreciated, thanks in advance

-Girst

**Comment by zeapo** [comment]
could you check whether your issue is related to #134

**Comment by girst** [comment]
It's not about SSH keys - I can't use HTTPS either. I talked to my friend who runs our server, he had the idea jgit might not accept startssl-signed certificates. 
I somehow managed to create a .git file in the specified path on the sdcard - but "Enable Git" is still greyed out. 

Does the app spit out a logfile or something?
thanks!

**Comment by fanningert** [comment]
Currently I get the same error, but I am not using GitLab. I am using (https://gogs.io/)[Gogs].
```
Message from jgit:
https://..../gogs/.....git: cannot open git-upload-pack
```

Protocol: **https**
Port: **443**
Authentication mode: **Username/Password**

**Comment by fanningert** [comment]
It looks like the encryption of android is the problem. I will test it know on a Nexus 5 with active device encryption.

**Comment by fanningert** [comment]
I found a nice side effect for the Nexus 6P (device encrypted). I copied the git pass directory (with the hidden .git directory and files) from my client laptop to an external directory on my phone. When I know synchronize the repository, it is working. So only the clone process make problems on a encrypted device (current only Nexus 6P is tested, test on Nexus 5 is on going).

**Test:**
*On the android Nexus 6P:*
* Add one new entry `test`
* Use `Synchronize the repository`: New entry is correct synchronized to the git server repository
*On the client laptop:*
* `pass git pull`
* `pass read test` (content is correct)
* `pass rm test`
* `pass git push`
*On the android Nexus 6P:*
* Use `Synchronize the repository`: No error, but the test entry is not removed.
* Use `Pull from remote`: test entry is removed and repository is synchron to the git server repository.

**Comment by girst** [comment]
I do not think device encryption is the culprit (at least in my case). 

The git client used in the app seems to have its own pool of root certificates, which does not include StartSSL (the only gratis cert provider afaik). 

I have moved my repository to my university's git server (also gitlab, , also over https, but cert signed by another authority) and it works flawlessly. 

The solution would be to allow selfsigned certs/add root certs.

**Comment by fanningert** [comment]
I don't use "StartSSL" certificate. My SSL certificate is from Hosteurope (GlobalSign). So I think the message is the same, but the problem is different.

**Comment by garyschulte** [comment]
Nexus 5X - I am unable to get any ssh auth working - whether I use ssh key pair generated by the app or one that already exists.  https works fine however. (but it is annoying to have to enter a password to get a password)

12-14 21:26:28.838  7653 10294 W System.err: org.eclipse.jgit.api.errors.TransportException: garyschulte@github.com:garyschulte/passStore.git: Auth fail
12-14 21:26:28.838  7653 10294 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
12-14 21:26:28.838  7653 10294 W System.err: 	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
12-14 21:26:28.838  7653 10294 W System.err: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
12-14 21:26:28.838  7653 10294 W System.err: 	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
12-14 21:26:28.838  7653 10294 W System.err: 	at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:44)
12-14 21:26:28.839  7653 10294 W System.err: 	at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:18)
12-14 21:26:28.839  7653 10294 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-14 21:26:28.839  7653 10294 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-14 21:26:28.839  7653 10294 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-14 21:26:28.839  7653 10294 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 21:26:28.839  7653 10294 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 21:26:28.839  7653 10294 W System.err: 	at java.lang.Thread.run(Thread.java:818)
12-14 21:26:28.839  7653 10294 W System.err: Caused by: org.eclipse.jgit.errors.TransportException: garyschulte@github.com:garyschulte/passStore.git: Auth fail
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
12-14 21:26:28.840  7653 10294 W System.err: 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
12-14 21:26:28.840  7653 10294 W System.err: 	... 11 more
12-14 21:26:28.840  7653 10294 W System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
12-14 21:26:28.841  7653 10294 W System.err: 	at com.jcraft.jsch.Session.connect(Session.java:512)
12-14 21:26:28.841  7653 10294 W System.err: 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
12-14 21:26:28.841  7653 10294 W System.err: 	... 18 more
12-14 21:26:28.878  7653  7653 I AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's

**Comment by garyschulte** [comment]
I forked and added some additional logging.  Tried with a 2kb manually generated rsa key which checks out fine from command line.  

12-15 02:07:49.619 26792-27534/com.zeapo.pwdstore D/JSch: Connecting to github.com port 22
12-15 02:07:49.734 26792-27534/com.zeapo.pwdstore D/JSch: Connection established
12-15 02:07:49.826 26792-27534/com.zeapo.pwdstore D/JSch: Remote version string: SSH-2.0-libssh-0.7.0
12-15 02:07:49.827 26792-27534/com.zeapo.pwdstore D/JSch: Local version string: SSH-2.0-JSCH-0.1.53
12-15 02:07:49.828 26792-27534/com.zeapo.pwdstore D/JSch: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
12-15 02:07:49.857 26792-27534/com.zeapo.pwdstore D/JSch: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
12-15 02:07:50.065 26792-27534/com.zeapo.pwdstore D/JSch: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
12-15 02:07:50.072 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_KEXINIT sent
12-15 02:07:50.072 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_KEXINIT received
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: ssh-dss,ssh-rsa
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: hmac-sha1,hmac-sha2-256,hmac-sha2-512
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: hmac-sha1,hmac-sha2-256,hmac-sha2-512
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: none,zlib,zlib@openssh.com
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: none,zlib,zlib@openssh.com
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: 
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: server: 
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: none
12-15 02:07:50.073 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: none
12-15 02:07:50.074 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: 
12-15 02:07:50.074 26792-27534/com.zeapo.pwdstore D/JSch: kex: client: 
12-15 02:07:50.074 26792-27534/com.zeapo.pwdstore D/JSch: kex: server->client aes128-ctr hmac-sha1 none
12-15 02:07:50.074 26792-27534/com.zeapo.pwdstore D/JSch: kex: client->server aes128-ctr hmac-sha1 none
12-15 02:07:50.080 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_KEX_ECDH_INIT sent
12-15 02:07:50.080 26792-27534/com.zeapo.pwdstore D/JSch: expecting SSH_MSG_KEX_ECDH_REPLY
12-15 02:07:50.186 26792-27534/com.zeapo.pwdstore D/JSch: ssh_rsa_verify: signature true
12-15 02:07:50.187 26792-27534/com.zeapo.pwdstore D/JSch: Permanently added 'github.com' (RSA) to the list of known hosts.
12-15 02:07:50.188 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_NEWKEYS sent
12-15 02:07:50.189 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_NEWKEYS received
12-15 02:07:50.196 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_SERVICE_REQUEST sent
12-15 02:07:50.294 26792-27534/com.zeapo.pwdstore D/JSch: SSH_MSG_SERVICE_ACCEPT received
12-15 02:07:50.387 26792-27534/com.zeapo.pwdstore D/JSch: Authentications that can continue: publickey,password
12-15 02:07:50.387 26792-27534/com.zeapo.pwdstore D/JSch: Next authentication method: publickey
12-15 02:07:50.692 26792-27534/com.zeapo.pwdstore D/JSch: Login trials exceeds 1
12-15 02:07:50.693 26792-27534/com.zeapo.pwdstore D/JSch: Disconnecting from github.com port 22
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err: org.eclipse.jgit.api.errors.TransportException: git@github.com:garyschulte/passStore.git: Auth fail
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:83)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:44)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at com.zeapo.pwdstore.git.GitAsyncTask.doInBackground(GitAsyncTask.java:18)
12-15 02:07:50.707 26792-27534/com.zeapo.pwdstore W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-15 02:07:50.708 26792-27534/com.zeapo.pwdstore W/System.err: Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:garyschulte/passStore.git: Auth fail
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
12-15 02:07:50.709 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
12-15 02:07:50.710 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
12-15 02:07:50.710 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
12-15 02:07:50.710 26792-27534/com.zeapo.pwdstore W/System.err: 	... 11 more
12-15 02:07:50.710 26792-27534/com.zeapo.pwdstore W/System.err: Caused by: com.jcraft.jsch.JSchException: Auth fail
12-15 02:07:50.711 26792-27534/com.zeapo.pwdstore W/System.err:     at com.jcraft.jsch.Session.connect(Session.java:512)
12-15 02:07:50.711 26792-27534/com.zeapo.pwdstore W/System.err:     at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
12-15 02:07:50.711 26792-27534/com.zeapo.pwdstore W/System.err: 	... 18 more

**Comment by bignose-debian** [comment]
The error is difficult for the developers and impossible for the users to even diagnose, because the message should not be this uninformative. Issue #219 requests better treatment of exceptions like this one.

**Comment by fradeve** [comment]
Got the same problem on a Nexus 5 encrypted LineageOS 7.1.1 (Nougat)

**Comment by KD0BPV** [comment]
I'm also getting this message. I think it's because my certificate is self-signed and/or expired. In my case, I need a way to bypass the SSL verification similar to running ```git config http.sslVerify "false"``` in the repo on a desktop; assuming I'm correct about what the problem is.

**Comment by 2114L3** [comment]
I am getting the same issue (4 years later). 
jgit cannot open git-upload-pack
using HTTPS to a local gogs signed with internal ca-root generated with hashicorp vault.
gogs logs shows  

> 2019/09/15 08:10:38 http: TLS handshake error from 192.168.1.31:58891: remote error: tls: unknown certificate

so it seems like the cert is being verified against a local CA stack, if there can be a 'do not validate cert option' 

Issue of:
> resulting URL the portnumber is preceded by a slash instead of a colon
still persists

**Comment by msfjarvis** [comment]
Please file a new issue with logs if this is still a problem on the newest Play Store release.
