### ISSUE TITLE
Possibility for repo (file name) encryption: support git-remote-gcrypt?

### ISSUE THREAD

**Issue by phryneas** [android-password-store/Android-Password-Store#165]
As this was discussed in #131 and the pass mailing list (http://lists.zx2c4.com/pipermail/password-store/2016-January/001884.html) right now I just wanted to suggest this.

https://github.com/joeyh/git-remote-gcrypt  would allow to encrypt the password-store (including file names) on the git remote (which seems to be something quite a few people want) and as it is just a remote helper program for git, it should work with desktop pass without any modifications.

It would need some auditing if it is really a secure solution (I have not checked it as I don't really need the feature myself), but maybe that would be something that could be included with relatively low overhead in Android-Password-Store?

**Comment by zeapo** [comment]
What we could do is encrypt the file names as suggested by @JasperWeiss. In the V2 we use an in-memory database for listing the files, i.e. we load the files structure in memory and list them. This allows us to have a faster switching between the categories (disk io). This also allows us to add a pre processing of the files, in this case decrypting the file names.

**Comment by JasperWeiss** [comment]
Would that still be compatible with pass?

**Comment by zeapo** [comment]
I'm not suggesting to encrypt them on the repo, but only on the storage.

The full process is not yet fully defined, and we'll open an issue on the other repo (when it's public) to discuss how to do it. 

For instance, during the clone, we might have to use a directory inside our app data as a buffer to avoid exposing the file names. The buffer is required because jgit writes directly to disk.
**Repo** -> **temp** -> *encrypt* -> **target directory**.

**Comment by JasperWeiss** [comment]
Just curious, what would be the benefit to encrypting the filenames locally? I guess it would prevent apps from reading the filenames.
However, the bigger problem is the fact that people on github can just look at my repository and see the list of accounts I have passwords for (that may for example include 'anonymous' accounts which the user whishes not to associate with their real identity)
Just my thoughts on this; It's a nice idea but is it worth the effort considering the minimal security gain? 
Perhaps the filenames could be encrypted using pgp just like the contents and have the user enter his password when opening the app. This would of course mean the same function needs to be implemented on pass but we could always ask the developer what he thinks about it?

**Comment by zeapo** [comment]
Only for local files indeed. This is only helpful for external folders. Is it worth the effort, I guess not. But if someone wants to work on it, he's welcome :)

I still think that no one should store his passwords in a public repository (like Github). Bitbucket offers free private repositories.

**Comment by maximbaz** [comment]
This topic often comes up in [browserpass](https://github.com/dannyvankooten/browserpass), there is definitely a demand for encrypting file names. To be clear, people want to encrypt the files on a _remote_ host, not in the local drive - it makes more sense, if your local host is compromised, your files will leak one way or another; and also because it is very popular these days to encrypt hard drive on all devices, so by stealing your laptop one would not see your files anyway. It is the remote that people don't want to trust, even if the remote promises privacy (like Bitbucket).

That's why saying "just put your files on Bitbucket / GitLab / Dropbox" is not a final solution, it requires trusting those services to keep the file names secure - but why should we trust, when instead we can hide this information entirely and put the encrypted folder wherever we want, even in a public GitHub repo.

I investigated the potential ways to encrypt file names on a remote, the most common suggestions are to use EncFS, LUKS or git-remote-gcrypt. In browserpass I recommend people to use one of these options too, however most people cannot do this just yet, because none of these options are implemented in the Android app.

This request is about `git-remote-gcrypt` and right now I personally like it the best, because it allows to use git push/pull for synchronizing repositories across devices - so Github, Gitlab and Bitbucket can all be used.

LUKS or EncFS require using a file sharing service, such as Dropbox, which I find less optimal - but an OK solution nonetheless. You already have a separate ticket requesting support for LUKS - #329.

**Comment by hyiltiz** [comment]
Do it is really a matter of whether gcrypt is supported by jgit. I wonder if Android Password Store can call Termux installed packages, in which case the user is only required to install gcrypt in Termux themselves; as pass is a cli oriented software, it might be safe to assume most users are comfortable with Termux.

**Comment by msfjarvis** [comment]
We cannot support git remote helpers with JGit.

**Comment by chmduquesne** [comment]
There is an open pull request for that, though: https://github.com/eclipse/jgit/pull/55

**Comment by msfjarvis** [comment]
> There is an open pull request for that, though: [eclipse/jgit#55](https://github.com/eclipse/jgit/pull/55)

And it has been open for 3 years with no response whatsoever. Even if it does get merged, we will not be able to use JGit 5 for many years still due to Android's lacklustre support for Java 8 APIs required by newer releases of JGit.

**Comment by chmduquesne** [comment]
Sad thing, but understandable.

I would find it brilliant if `git-remote-gcrypt` could be supported because it would become totally safe to store passwords in a public repo, but one needs to be pragmatic.

Thanks for clarifying!
