### ISSUE TITLE
Feature request: PIN (or password) to open app

### ISSUE THREAD

**Issue by brianbuccola** [android-password-store/Android-Password-Store#190]
Hi,

First off, many thanks for this app -- I just started using it today, and am liking it very much so far.

I was wondering if there are any plans to add a way to (optionally) create a PIN (or password) that is required to open the app, such as what exists on the Dropbox app. The purpose would be twofold:
1. Even though each entry is encrypted, anyone who gains access to the phone can nevertheless open the app and read the names of the entries and directories, which, depending on the user's naming conventions, can give away quite a bit of info (at the very least, which websites, etc. the user has accounts on). A PIN would add a layer between prying eyes and this info.
2. There could then be an option where, if the PIN is entered incorrectly more than, say, 5 times, then all app data is deleted.

Thoughts?

Brian

**Comment by DSIW** [comment]
That's a nice idea, because I don't want to offer my sites where I have accounts, too.

I won't delete all data. I think it's better if the user can't unlock the app after an specific time which increases (maybe double) after every 3 attempts. This is the same behavior as the standard Android system locking screen.

Implementation:
Can it be a normal activity which accepts only the right PIN or is it more complicated? Of course the initial PIN should be set and can be changed by user. Maybe the [AppIntro](https://github.com/PaoloRotolo/AppIntro) lib can be useful for initial setting.

**Comment by jumper047** [comment]
Somewhere on tracker was issue about encryption of the file names. I think it is more useful in this situation. PIN can't help here, because this is about data format. For example,I use syncthing for synchronization, and names can be read with any file manager, without launching app.

**Comment by zeapo** [comment]
How about [Serrure](https://play.google.com/store/apps/details?id=com.sp.protector.free&feature=related_apps)? It can be used to lock the application.

**Comment by msfjarvis** [comment]
Fixed with https://github.com/android-password-store/Android-Password-Store/pull/541
