### ISSUE TITLE
OpenKeyChain PGP key prompt doesn't show up when I select a password in the store

### ISSUE THREAD

**Issue by nemoload** [android-password-store/Android-Password-Store#386]
I have the latest version of both the applications and they are running on Android 7.0

**Comment by pLesur** [comment]
Happens to me after updating (either openkeychain or password store, I don't really).

**Comment by mkapostolov** [comment]
Opening the Password Store and clicking on an entry directly shows the entry data - password, username... without asking for OpenKeyChain PGP password. 

This is a major security issue since everybody with access to the phone can have access to all stored items (passwords) in the Password Store without being prompted for the master password stored in the OpenKeyChain key.

Here is my setup:
- Password Store version: 1.2.0.75
- OpenKeychain version: 5.2 (52009)
- Device: Samsung Galaxy S8+
- Android: 8.0.0

**Comment by pLesur** [comment]
The problem I had (hasn't happened in a while though) was that the prompt didn't appear and *nothing* happened. So it wasn't much of a security issue as a cannot-do-anything issue (I had to delete my private key from OpenKeychain and reimport it).
OP didn't make it clear what the actual issue was...

**Comment by rebootl** [comment]
Uhm, sorry for the stupid question but where can i configure openkeychain, not to cache the passphrase? Can't find it D:
I've got v5.2 on android.

**Comment by Schnilz** [comment]
i have the same issue ... the prompt from OpenKeychain doesn't show up. Only after i open the OKC app and let it running the prompt shows up and i can copy passwords. 

Other apps like TermBot have the same issue (ssh keys form dont load as the OKC prompt doesnt show up . Maybe this is actually an OKC issue ?

**Comment by Skrilltrax** [comment]
@Schnilz have you checked #518 , this might be the same issue. Please also try and report if the solution mentioned there fixes the issue.

**Comment by Schnilz** [comment]
thanks! that was it. I own a OnePlus 3T ... disabling the battery optimizing did the trick
