### ISSUE TITLE
Doesn't show hidden folders anymore

### ISSUE THREAD

**Issue by Adonai** [android-password-store/Android-Password-Store#446]
I use APS directly with my dotfiles repo. Starting with 1.3.x it doesn't see .password-store folder, nor does it see any other dot folder.

**Comment by zidhuss** [comment]
The reason for this change is here: https://github.com/zeapo/Android-Password-Store/pull/424#issuecomment-421176048.

**Comment by zeapo** [comment]
We should add the option to add them back.

**Comment by zidhuss** [comment]
Sure, I could add a preference for it.

**Comment by Adonai** [comment]
Thanks, appreciate that!

**Comment by Adonai** [comment]
Any progress on this? If you don'thave time I can come up with a PR myself, just point me where to look at.

**Comment by etu** [comment]
I have a suggestion that would not imply adding an option to show hidden directories and would probably benefit people like me, my wife, @Adonai and others with setups like this.

It would be nice to have an option to select default folder to look at when you open the app up. And of course that folder should be able to be a hidden folder. That way people with other directory structures could set this option and get in there directly. And then the problem with hidden files and directories is most probably gone because I don't think people in general use hidden files or directories inside of their password-store.

**Comment by FruitieX** [comment]
I too store my .password-store folder directly in a git repo. As such I can't use the app after the latest update which ignores hidden folders.

**Comment by etu** [comment]
@FruitieX Protip: I pulled down the apk from this release https://github.com/zeapo/Android-Password-Store/releases/tag/v1.2.0.75 and use that. Then I've disabled auto-updates for this app in Play Store and will never be able to hit the "Upgrade all" button until there's a proper fix for this.
