### ISSUE TITLE
[BUG] Username is not deduced from name of folder with new autofill

### ISSUE THREAD

**Issue by cole-h** [android-password-store/Android-Password-Store#657]
**Describe the bug**
(Disclaimer: I didn't use the previous accessibility-based autofill, so this might have been a problem back then as well.)

I just installed the snapshot that includes the new Oreo Autofill from #653. So far, it's great! The only complaint I have is that it uses the name of the file to autofill the username and password. Here's an example of my structure:

```
.password-store
`-- Internet
     `-- github.com
          `-- cole-h
               `-- password
```

However, when I search for autofill entries on `github.com`, it only shows the `password` file (and then fills in the username as `password`, while reading the password from the file).

**To Reproduce**
1. Go to `github.com/login`
2. Search for entries to autofill
3. Tap the `password` file of the `cole-h` entry
4. Note that it fills the username as `password`

**Expected behavior**
I expect autofill to be able to take the name of the parent folder as the username, and the contents of the `password` file as the password. The best way to do this would probably be a setting (or maybe not; I have no experience with mobile app development).

**Screenshots**
![Screenshot_20200324-110339_Firefox Nightly](https://user-images.githubusercontent.com/28582702/77461445-c9338780-6dbf-11ea-818c-a25f8e94ab25.jpg)

**Device information (please complete the following information):**
 - Device: Galaxy S9
 - OS: One UI 2.0, Android 10
 - App version: latest snapshot as of 24 March 2020 at 10:57AM PDT

**Comment by msfjarvis** [comment]
Thanks for bringing this up. Because everybody's folder layout varies, it's difficult to support all use cases in the first attempt. Currently we only have logic for cases like this in the save dialog, where we let the user choose between having their username be the filename of the final password file, or have it encrypted within that file and let them use an arbitrary filename. I believe we should also offer a similar choice in the filling logic. Assigning to Fabian since he's maintaining the autofill feature.

**Comment by FabianHenneke** [comment]
I wasn't aware of this type of directory structure, but now saw that it is even listed as an example on the official pass page.

I will most likely add a setting that allows switching between a file-based (default) and directory-based (what you are using) structure for the Password Store repository. I will then make search, fill and save respect this setting as far as possible.

**Comment by FabianHenneke** [comment]
I have added a configuration option which switches between the two style and adapts all Autofill operations accordingly in #660.

@cole-h Since this introduces a lot of additional logic in all Autofill operations and I don't use the newly implemented directory layout myself, it you could test this before it gets merged.
