### ISSUE TITLE
HTTPS password not being persisted correctly

### ISSUE THREAD

**Issue by msfjarvis** [android-password-store/Android-Password-Store#725]
Even after toggling the setting on I cannot get any of my devices (confirmed by multiple users as well) to persist the HTTPS password correctly. On every new operation the password returned from encryptedSettings is null again. I added some logging with https://github.com/android-password-store/Android-Password-Store/commit/e651cd768aeca118e154487c70a41409b04c0946 to verify this, and have confirmed that its not being removed on the `onError` path. I cannot fathom any reason for this and it is driving me mad.

**Comment by msfjarvis** [comment]
Problem runs far deeper. Protocol validation is completely broken. With the newest logging commit to `cleanups` branch I see this in my logs and the previously working config options are reported as broken now. Maybe `java.net.URL` is not as good at this as I hoped...

`D  Malformed URL encountered: msfjarvis@192.168.0.102/home/msfjarvis/.password-store`

**Comment by msfjarvis** [comment]
Reverting #723 does not fix this problem :/ Gonna look at this in the morning with hopefully better insight into what is wrong. Too confused right now.

**Comment by FabianHenneke** [comment]
My findings:

1. Running a Git command from the options menu with an invalid setup in GitServerConfigActivity crashes APS since `url` in `BaseGitActivity` is not initialized - I would vote for turning it into a proper nullable variable so that we can handle the nullability in all the Git operations. The fact that `url` has to be a nullable var means a lot of `!!` and `?`, but I currently don't see a way around this.

2. `java.net.URL` requires a protocol, which means that we can only use it to validate in the very end. Furthermore, it does not know the `ssh` protocol, so we need to use `java.net.URI` instead.

Very roughly, this is something you could base your fix on, but there may still be other issues: https://github.com/android-password-store/Android-Password-Store/commit/51ca060d9be9fab71c626e458b8d036523ada61e
