### ISSUE TITLE
[FEATURE] webdav integration

### ISSUE THREAD

**Issue by szaimen** [android-password-store/Android-Password-Store#831]
**Is your feature request related to a problem? Please describe.**
In the moment I have to rely on 3rd party apps like Nextcloud, Owncloud or other to sync my database.

**Describe the solution you'd like**
Would be really nice if there was a webdav synchronisation integrated into the app, since the apps I mentioned aren't really reliable in syncing files.

**Describe alternatives you've considered**
Currently nothing

**Additional context**
Currently nothing

**Comment by FabianHenneke** [comment]
Could you describe the issues that led you to say that these apps are not really reliable? I think that we would have a hard time building any kind of file synchronization into Password Store that would be more reliable than dedicated third party apps such as Nextcloud.

**Comment by szaimen** [comment]
The problem is that those apps don't support 2-way synchronisation to my knowledge and cannot be trusted with a file that must be synchronized frequently - that is at least my experience.

Concerning Nextcloud: only their desktop client is able to synchronize files reliable in my experience but not their android app.

**Comment by FabianHenneke** [comment]
Have you tried syncing with Git and if so, is there something we could do to improve your experience with it?

**Comment by szaimen** [comment]
No, I haven't tried syncing with git because I have already a Nextcloud installation and would like to use that and not git...

**Comment by FabianHenneke** [comment]
I don't want to force you to use git instead, but please consider the following: Two-way synchronization via WebDAV seems to be a difficult problem that is unlikely to be solved by us in a satisfactory way if Nexcloud's and Owncloud's own apps fail to do so. Git, by design, is all about making sure synchronization is performed reliably and is both well integrated into the app and well tested.

Unless someone with a very good understanding of the WebDAV protocol comes along and submits a suitable PR, I don't think that we will be able to implement support for it, and thus Git may be your best bet for now.

@msfjarvis Do you know anyone who is knowledgeable about WebDAV and an active user of APS?

**Comment by msfjarvis** [comment]
> I don't want to force you to use git instead, but please consider the following: Two-way synchronization via WebDAV seems to be a difficult problem that is unlikely to be solved by us in a satisfactory way if Nexcloud's and Owncloud's own apps fail to do so. Git, by design, is all about making sure synchronization is performed reliably and is both well integrated into the app and well tested.
> 
> Unless someone with a very good understanding of the WebDAV protocol comes along and submits a suitable PR, I don't think that we will be able to implement support for it, and thus Git may be your best bet for now.
> 
> @msfjarvis Do you know anyone who is knowledgeable about WebDAV and an active user of APS?

**Comment by msfjarvis** [comment]
I've given this some more thought and I don't think I'm going to consider adding WebDAV to the app at all regardless of who's writing the implementation. If first-party vendors cannot get this right then I most certainly don't want to maintain it alongside the existing labyrinth of Git.
