### ISSUE TITLE
[FEATURE] Make it easy to re-encrypt with new pgp keys

### ISSUE THREAD

**Issue by posix4e** [android-password-store/Android-Password-Store#838]
**Is your feature request related to a problem? Please describe.**
I want to be able to create a new key to use

**Describe the solution you'd like**
I've already created the key and hooked it up, I can manually trigger it by opening and closing each password editing it, and it will get the new key. It would be better if there's a button which could do this automatically for all my keys. Simliar to pass init <gpg key> <gpg key2>

**Describe alternatives you've considered**
Doing it on my laptop

**Comment by msfjarvis** [comment]
How `pass` operates on Linux versus how `Password Store` operates on Android are too different for us to be able to implement this satisfactorily. OpenKeychain results can often be slow and since we bind a reactive UI to those results re-encrypting every single password is going to be a time-consuming process with little incentive when doing it with `pass` is much more straightforward. If someone from the community wishes to take a stab at it then I'm more than happy to review the PR, but as of now this won't be fixed by the maintainers.

**Comment by posix4e** [comment]
Totally understandable!
