### ISSUE TITLE
Imperfect German language support

### ISSUE THREAD

**Issue by Schueni1** [android-password-store/Android-Password-Store#839]
In the settings section the german language support is a bit patchy.  
Some options are in english others are in german.  
I think, if it is too much work to maintain multiple languages I would just remove language support for them and have everything in english. This would be absolutely fine for me, but the mix of languages is a bit weird :stuck_out_tongue_winking_eye:

![](https://i.imgur.com/D0RcfOW.jpg)

**Comment by msfjarvis** [comment]
Localisation is done by volunteers, not us. We're in the process of migrating this to Crowdin.com to make it easier for users to contribute and once we have a few proofreaders we'll be able to have consistent translations. Leaving this open as a reminder to finish moving to Crowdin but there's not much I can do right now other than obliterating all translations since none of them are incomplete.

**Comment by msfjarvis** [comment]
There's nothing for us to do here so I'm closing this, if you are able to, feel free to update the translations through the Crowdin link in our readme file.
